jobs:
  - name: gh-proxy-mgmt-dev
    max_in_flight: 1
    plan:
      - get: dataworks-aws-external-batch
        trigger: true
      - get: emr-al2-ami
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: github_proxy
      - .: (( inject meta.plan.terraform-apply ))
        config:
          run:
            dir: 'dataworks-aws-external-batch/terraform/deploy/github_proxy'
      - .: (( inject meta.plan.terraform-plan ))
        config:
          run:
            dir: 'dataworks-aws-external-batch/terraform/deploy/github_proxy'
