jobs:
  - name: dataworks-aws-external-batch-pr
    plan:
      - get: dataworks-aws-external-batch-pr
        trigger: true
        version: every
      - put: dataworks-aws-external-batch-pr
        params:
          path: dataworks-aws-external-batch-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-aws-external-batch: dataworks-aws-external-batch-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          dataworks-aws-external-batch: dataworks-aws-external-batch-pr
        params:
          TF_WORKSPACE: "qa"
          DETAILED_EXITCODE: ""
        on_failure:
          put: dataworks-aws-external-batch-pr
          params:
            path: dataworks-aws-external-batch-pr
            status: failure
        on_success:
          put: dataworks-aws-external-batch-pr
          params:
            path: dataworks-aws-external-batch-pr
            status: success
